version: '3.8'

services:
  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bank
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
  app:
    build:
      context: ./accountManagement/
    ports: 
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
    links:
      - postgres
      
volumes:
  pg_data:
