spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/bank
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:liquibase/changelog.xml

